// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKekJwaI7ggkAezhdWWcAFlMmkvf8NT9I',
    appId: '1:122536634837:web:7c44acf91950620acb355c',
    messagingSenderId: '122536634837',
    projectId: 'connectuni-48a92',
    authDomain: 'connectuni-48a92.firebaseapp.com',
    storageBucket: 'connectuni-48a92.appspot.com',
    measurementId: 'G-KSMNVC7JT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEmsYUXeX9ZK6DBh6GydI9D9h0wukM1k',
    appId: '1:122536634837:android:b839b2f53d7fb6eccb355c',
    messagingSenderId: '122536634837',
    projectId: 'connectuni-48a92',
    storageBucket: 'connectuni-48a92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8f-DXXoGQHH6HYKphFGYncfCOjLJeXvQ',
    appId: '1:122536634837:ios:fcdcc6feaaaeefbbcb355c',
    messagingSenderId: '122536634837',
    projectId: 'connectuni-48a92',
    storageBucket: 'connectuni-48a92.appspot.com',
    iosBundleId: 'com.connectuni.connectuni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8f-DXXoGQHH6HYKphFGYncfCOjLJeXvQ',
    appId: '1:122536634837:ios:32f72ae9dc8f0ee2cb355c',
    messagingSenderId: '122536634837',
    projectId: 'connectuni-48a92',
    storageBucket: 'connectuni-48a92.appspot.com',
    iosBundleId: 'com.connectuni.connectuni.RunnerTests',
  );
}
